default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: co-pay-api_development

test:
  <<: *default
  database: co-pay-api_test

production:
  <<: *default
  database: co-pay-api_production
  username: co-pay-api
  password: <%= ENV['CO-PAY-API_DATABASE_PASSWORD'] %>
